### ISSUE TITLE
Feature request: minimize to tray

### ISSUE THREAD

**Issue by pavelicii** [shaobaili3/LoR_Master#12]
Thank you for the great application! One cool thing to have in the next releases: the ability to minimize the app to tray.

**Comment by shaobaili3** [comment]
Thanks for your feedback!
Minimizing to tray is very important.
We will add this feature soon in version 0.9.9

**Comment by shaobaili3** [comment]
#17 feature added

**Comment by pavelicii** [comment]
Sorry, but how do I minimize the app to the Tray? I mean I have a Tray icon now, but when I minimize the app, it is also still in the Task Bar.
