### ISSUE TITLE
Selecting multiple decks on filtering match history

### ISSUE THREAD

**Issue by monkollek** [shaobaili3/LoR_Master#22]
Great work with the deck tracker it's awesome. This isn't an issue but more a feature request.

Currently, the match history allows you to either pick one deck or all decks (i.e. no deck selected).
Would you be able to implement the ability to select multiple decks (e.g. alt, shift, ctrl + click) from the horizontal scroll pane?

Or the ability to collapse into archetypes so similar to the other request in the issue list.
Thanks!

**Comment by painttist** [comment]
Thanks for your feature suggestion! We are planning to implement much better filtering function soon (in next release probably) as we now support up to 100 match histories.
