### ISSUE TITLE
Feature: Displaying probability of drawing a card on the tracker

### ISSUE THREAD

**Issue by lucas-abbate** [shaobaili3/LoR_Master#27]
Hi! Awesome job. In my opinion, this Tracker is almost perfect, expecting that it doesn't calculates the chances of drawing x card.
It would be great if the tracker shows the chances of drawing a wanted card depending on the copies you currently have on your deck.
I would try to develop it myself, but I've never worked with Open source so don't expect something big
Thanks and keep with the great job!

**Comment by painttist** [comment]
Thank you for using our tracker and sharing your feedback! I agree that showing the chances of drawing x card would be quite cool. The only slight issue is that we don't have enough information about the remaining cards (especially when cards are shuffled into, created, or tossed) to be remotely certain about the chances of drawing certain cards. We don't want to mislead players.

But we will definitely look into other ways of building tools to help with these calculations, maybe like an easy to use calculator that you can manually adjust the remaining cards. Probably after we settles with dealing with our meta & deck library feature. Anyways, thanks for sharing with us!
