### ISSUE TITLE
Questions about the internal API

### ISSUE THREAD

**Issue by m0t0k1ch1** [shaobaili3/LoR_Master#46]
Hi, I'm a developer trying to implement an application based on the Riot API.

I think the Riot API does not provide the endpoint to get a LoR player's `puuid` or `tagLine` from his/her `gameName`, but your API server has an endpoint that returns a `tagLine` from the player's `gameName`.

ex. https://lormaster.herokuapp.com/names/apac/m0t0k1ch1

The README states the following, but I think the above endpoint can not be implemented with only the data provided by the Riot API.

> **A.** This project is approved by [Riot](https://www.riotgames.com/en/DevRel/rso), and registered in the [Riot Development Portal](https://developer.riotgames.com/). All data source is from [Riot API](https://developer.riotgames.com/apis) and [LoR Data Dragon](https://developer.riotgames.com/docs/lor). There is **NO** third-party data source.

My questions are below:

- How is the above endpoint implemented?
- Can I use the above endpoint for personal use?

**Comment by shaobaili3** [comment]
Hi,

- Riot API provides match history which contains tagLine and gameName. The tagLine can be found from a certain amount of match history via the gameName.

- You can use this endpoint for personal usage.

**Comment by m0t0k1ch1** [comment]
@shaobaili3 Thank you so much!!! 🙏🙏🙏
